version: "3.7"
services:
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
  ###########################
  # Zipkin state store
  ###########################
  zipkin:
    image: jaegertracing/all-in-one:1.21
    ports:
      - "16686:16686"
  ############################
  # Gateway app + Dapr sidecar
  ############################
  gateway:
    image: ankur198/nagp-apigateway
    ports:
      - "5000:80"
    depends_on:
      - placement
  gateway-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - gateway
  ############################
  # User app + Dapr sidecar
  ############################
  user:
    image: ankur198/nagp-userservice
    depends_on:
      - placement
  user-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - user
  ############################
  # Order app + Dapr sidecar
  ############################
  order:
    image: ankur198/nagp-orderservice
    depends_on:
      - placement
    networks:
      - hello-dapr
  order-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - order
  ############################
  # Notification app + Dapr sidecar
  ############################
  notification:
    image: ankur198/nagp-notificationservice
    depends_on:
      - placement
    networks:
      - hello-dapr
  notification-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - notification
  ############################
  # Catalog app + Dapr sidecar
  ############################
  catalog:
    image: ankur198/nagp-catalogservice
    depends_on:
      - placement
    networks:
      - hello-dapr
  catalog-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - catalog