version: "3.7"
services:
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    ports:
      - "50006:50006"
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
  ###########################
  # Zipkin state store
  ###########################
  zipkin:
    image: jaegertracing/all-in-one:1.21
    ports:
      - "16686:16686"
  ############################
  # Gateway app + Dapr sidecar
  ############################
  gateway:
    build: ./Src/ApiGateway
    ports:
      - "5000:80"
    depends_on:
      - placement
  gateway-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - gateway
  ############################
  # User app + Dapr sidecar
  ############################
  user:
    build: ./Src/UserService
    depends_on:
      - placement
  user-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - user
  ############################
  # Order app + Dapr sidecar
  ############################
  order:
    build: ./Src/OrderService
    depends_on:
      - placement
    networks:
      - hello-dapr
  order-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - order
  ############################
  # Notification app + Dapr sidecar
  ############################
  notification:
    build: ./Src/NotificationService
    depends_on:
      - placement
    networks:
      - hello-dapr
  notification-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - notification
  ############################
  # Catalog app + Dapr sidecar
  ############################
  catalog:
    build: ./Src/CatalogService
    depends_on:
      - placement
    networks:
      - hello-dapr
  catalog-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - catalog