version: "3.7"
services:
  ############################
  # Gateway app + Dapr sidecar
  ############################
  gateway:
    build: ./Src/ApiGateway
    ports:
      - "5000:80"
    depends_on:
      - redis
      - placement
      - zipkin
      - user-dapr
    networks:
      - hello-dapr
  gateway-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "gateway",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-dapr-http-port", "50123",
     "-config", "/configuration/tracing.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - gateway
    network_mode: "service:gateway"
  ############################
  # User app + Dapr sidecar
  ############################
  user:
    build: ./Src/UserService
    depends_on:
      - redis
      - placement
      - zipkin
    networks:
      - hello-dapr
  user-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "user",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-config", "/configuration/tracing.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - user
    network_mode: "service:user"
  ############################
  # Order app + Dapr sidecar
  ############################
  order:
    build: ./Src/OrderService
    depends_on:
      - redis
      - placement
      - zipkin
    networks:
      - hello-dapr
  order-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "order",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-config", "/configuration/tracing.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - order
    network_mode: "service:order"
  ############################
  # Notification app + Dapr sidecar
  ############################
  notification:
    build: ./Src/NotificationService
    depends_on:
      - redis
      - placement
      - zipkin
    networks:
      - hello-dapr
  notification-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "notification",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-config", "/configuration/tracing.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - notification
    network_mode: "service:notification"
  ############################
  # Catalog app + Dapr sidecar
  ############################
  catalog:
    build: ./Src/CatalogService
    depends_on:
      - redis
      - placement
      - zipkin
    networks:
      - hello-dapr
  catalog-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "catalog",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-config", "/configuration/tracing.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - catalog
    network_mode: "service:catalog"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - hello-dapr
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - hello-dapr
  ############################
  # Zipkin state store
  ############################
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - hello-dapr
networks:
  hello-dapr: