version: "3.7"
services:
  ############################
  # Dapr placement service
  ############################
  placement:
    command: ["./placement", "-port", "50006"]
    networks:
      - hello-dapr
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    networks:
      - hello-dapr
  ###########################
  # Zipkin state store
  ###########################
  zipkin:
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9412
    networks:
      - hello-dapr
  ############################
  # Gateway app + Dapr sidecar
  ############################
  gateway:
    build: ./Src/ApiGateway
    networks:
      - hello-dapr
  gateway-dapr:
    command: ["./daprd",
     "-app-id", "gateway",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-dapr-http-port", "50123",
     "-config", "/configuration/tracing.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    network_mode: "service:gateway"
  ############################
  # User app + Dapr sidecar
  ############################
  user:
    build: ./Src/UserService
    networks:
      - hello-dapr
  user-dapr:
    command: ["./daprd",
     "-app-id", "user",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-config", "/configuration/tracing.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    network_mode: "service:user"    
  ############################
  # Order app + Dapr sidecar
  ############################
  order:
    build: ./Src/OrderService
    networks:
      - hello-dapr
  order-dapr:
    command: ["./daprd",
     "-app-id", "order",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-config", "/configuration/tracing.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    network_mode: "service:order"
  ############################
  # Notification app + Dapr sidecar
  ############################
  notification:
    build: ./Src/NotificationService
    networks:
      - hello-dapr
  notification-dapr:
    command: ["./daprd",
     "-app-id", "notification",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-config", "/configuration/tracing.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    network_mode: "service:notification"
  ############################
  # Catalog app + Dapr sidecar
  ############################
  catalog:
    build: ./Src/CatalogService
    networks:
      - hello-dapr
  catalog-dapr:
    command: ["./daprd",
     "-app-id", "catalog",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-config", "/configuration/tracing.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    network_mode: "service:catalog"
networks:
  hello-dapr: